const express = require('express')
const startSprintHandler = require('./app/handlers/startSprintHandler')
const getActivitiesByGroupingHandler = require('./app/handlers/getActivitiesByGroupingHandler')
const endSprintHandler = require('./app/handlers/endSprintHandler')
const createCardHandler = require('./app/handlers/createCardHandler')
const getCardsHandler = require('./app/handlers/getCardsHandler')
const getSprintInfoHandler = require('./app/handlers/getSprintInfoHandler')
const getSprintInfoByIdHandler = require('./app/handlers/getSprintInfoByIdHandler')
const deleteCardHandler = require('./app/handlers/deleteCardHandler')
const updateCardHandler = require('./app/handlers/updateCardHandler')
const createActivitiesByGroupingHandler = require('./app/handlers/createActivitiesByGroupingHandler')
const verifyActvitiesByGroupingHandler = require('./app/handlers/verifyActvitiesByGroupingHandler')
const getReviewBacklogHandler = require('./app/handlers/getReviewBacklog')
const routes = express.Router()

// Server routes
routes.get('/', (req, res) => res.status(200).json({ message: 'Up and running!' }))
routes.post('/startSprint', startSprintHandler)
routes.get('/getActivitiesByGrouping', getActivitiesByGroupingHandler)
routes.put('/endSprint', endSprintHandler)
routes.post('/createCard', createCardHandler)
routes.get('/getCards', getCardsHandler)
routes.get('/getSprintInfo', getSprintInfoHandler)
routes.get('/getSprintInfoById', getSprintInfoByIdHandler)
routes.delete('/deleteCard', deleteCardHandler)
routes.put('/updateCard', updateCardHandler)
routes.post('/createActivitiesByGrouping', createActivitiesByGroupingHandler)
routes.get('/verifyActvitiesByGrouping', verifyActvitiesByGroupingHandler)
routes.get('/getReviewBacklog', getReviewBacklogHandler)

module.exports = routes
